name: azure
channels:
- conda-forge
- defaults
dependencies:
- python=3.7
- pip
- jupyter
- jupyter_contrib_nbextensions
- pandas
- matplotlib
- scikit-learn
- numpy
- pip:
    - azureml-sdk
    - azureml-automl-runtime
    - azureml-train-automl-runtime
    - azureml-widgets
